### ISSUE TITLE
Error when running wails dev.

### ISSUE THREAD

**Issue by kuchaow** [LGiki/wails-template-nextjs#1] opened 2022-11-03 22:57 UTC
I encounter this error when I first try to run "wails dev":

ERROR: 
main.go:14:12: pattern frontend/out/*: cannot embed directory frontend/out/*: invalid name *

The way to replicate it is to make a new project with the template command, then solve the first issue of incorrect labeling in the main.go file from "RBG" to "BackgroundColour" and then run "wails dev".

**Comment by LGiki** [comment] 2022-11-05 07:46
Thanks for reporting this issue, the problem with `RGBA` has been fixed.
But I can't reproduce the error you mentioned, can you please provide the output of running `wails dev`?

**Comment by gmharrison** [comment] 2022-11-16 18:56
I'm encountering the same problem while running `wails dev`. Here is the output I'm seeing, along with the directory that has been created called `*`.

<img width="171" alt="Screen Shot 2022-11-16 at 1 55 11 PM" src="https://user-images.githubusercontent.com/17712022/202268629-85dc6425-5620-438a-9864-bc3087d3ba56.png">
<img width="674" alt="Screen Shot 2022-11-16 at 1 55 01 PM" src="https://user-images.githubusercontent.com/17712022/202268632-e691e106-1c20-4c50-acaa-31e5bbc43aa1.png">

**Comment by jbrodriguez** [comment] 2022-11-16 20:56
have the same error, removed the `*` from the go:embed directive and it seems to be working fine, not sure about build time though

**Comment by siddmo** [comment] 2022-12-02 23:43
Have you guys found any resolution?

Update: I got it working with `go:embed all:frontend/out`

**Comment by LGiki** [comment] 2022-12-29 01:51
Sorry, I was busy with some personal matters and did not deal with this issue in time.
Many thanks to @siddmo and @lunarca . I just merged the PR from @lunarca  and this issue should be solved now. :rocket:

**Closed as completed by LGiki** 2022-12-29 01:51 UTC
Labels: bug
